### ISSUE TITLE
为什么这个看板娘不能通过图灵测试？

### ISSUE THREAD

**Issue by RayleighZ** [Kying-star/ReactNative-live2d#1]
还是不够职能，以你的能力应该是可以做到的

**Comment by Kying-star** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
